_format_version: "2.1"

services:
  - name: auth-v1
    url: http://auth:9999
    routes:
      - name: auth-v1
        paths:
          - /auth/v1
        strip_path: false

  - name: rest-v1
    url: http://rest:3000
    routes:
      - name: rest-v1
        paths:
          - /rest/v1
        strip_path: false

  - name: realtime-v1
    url: http://realtime:4000
    routes:
      - name: realtime-v1
        paths:
          - /realtime/v1
        strip_path: false

  - name: storage-v1
    url: http://storage:5000
    routes:
      - name: storage-v1
        paths:
          - /storage/v1
        strip_path: false

  - name: functions-v1
    url: http://functions:8081
    routes:
      - name: functions-v1
        paths:
          - /functions/v1
        strip_path: false

  - name: meta
    url: http://meta:8080
    routes:
      - name: meta
        paths:
          - /pg
        strip_path: true
